### ISSUE TITLE
CRAN error

### ISSUE THREAD

**Issue by LucyMcGowan** [LucyMcGowan/tipr#21]
@malcolmbarrett I got an email this morning that we need to make an updated in order to stay on CRAN based on an error on one of their checks: 

https://cran.r-project.org/web/checks/check_results_tipr.html

It looks like it is only seen on one machine: 

Version: 1.0.1 
Check: examples 
Result: ERROR 
  Running examples in ‘tipr-Ex.R’ failed
  The error most likely occurred in:
 ```r
base::assign(".ptime", proc.time(), pos = "CheckExEnv")
### Name: adjust_hr
### Title: Adjust an observed hazard ratio for a normally distributed
###   confounder
### Aliases: adjust_hr adjust_hr_with_continuous

### ** Examples

adjust_hr(0.9, -0.9, 1.3) 
```
Error in eval(call("force", as.symbol(paste0("..", x)))) : 
argument "..8" is missing, with no default
Calls: adjust_hr ... glue_data -> lapply -> FUN -> %||% -> eval -> eval -> force
Execution halted
Flavor: [r-devel-linux-x86_64-debian-gcc](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-gcc/tipr-00check.html)

I can't seem to replicate it myself on my machine -- do you have an ideas on how we might fix this? (maybe we can chat on our next call)

**Comment by malcolmbarrett** [comment]
It seems to be propogating on the devel version -- four errors now! I can try to install that version of R locally to see if I can replicate it. In the meantime, I ran

```r
library(tipr)
debug(glue::glue_data)
adjust_hr(0.9, -0.9, 1.3)
undebug(glue::glue_data)
```

But the information I got from it was limited. It seems to me like it's from the cli call

**Comment by malcolmbarrett** [comment]
It might be helpful to post on the cli repo if so

**Comment by malcolmbarrett** [comment]
This seems to be an r-devel issue, but I can't replicate it locally using R-devel for mac 🤔

**Comment by malcolmbarrett** [comment]
Ah! It's a glue issue about trailing commas https://github.com/tidyverse/glue/issues/320

**Comment by malcolmbarrett** [comment]
Except I can't find any in tipr on a first pass 🙃. Maybe the error is being triggered in another way? I am able to replicate the error in the linked issue, so at least there is that

**Comment by malcolmbarrett** [comment]
There are a lot of changes here since the last CRAN release, so I'm going try running the dev version on CRAN's windows devel machine

**Comment by malcolmbarrett** [comment]
I can finally replicate this using the CRAN version of tipr. Pretty sure we've already fixed it and just need to do a release 😎
