### ISSUE TITLE
Changing argument names

### ISSUE THREAD

**Issue by malcolmbarrett** [LucyMcGowan/tipr#9]
`effect` -> `effect_observed`
`smd` -> `confounder_exposure_effect` (in the docs: `model(u ~ t)`)
`outcome_association` -> `outcome_confounder_effect` (in the docs: `model(y ~ t + z + u)`)

**Comment by malcolmbarrett** [comment]
`exposed_p` -> `confounder_exposed_prev`
`unexposed_p` -> `confounder_unexposed_prev`

**Comment by LucyMcGowan** [comment]
`exposure_confounder_effect`
`confounder_outcome_effect`
